### PR TITLE
[Update] Add support for execution limit by number of steps

### LINKED ISSUE #51: Setting time-bound on execution of code
I am looking to use Sval in an educational context and would like to know if there is any way to set a time-bound on how long the evaluated code can run for? This would be helpful if the evaluated code has an infinite loop.

An older project (JS-Interpreter) handles this use case "by calling the step function a maximum number of times, or by calling step indefinitely many times but using a setTimeout between each call to ensure other tasks have a chance to execute". I wonder if there's something I can do in Sval like this?

### PR DESCRIPTION
**Pull request by rohanchandra**
Allows the user to set a limit on the number of steps to execute before throwing an error.

Fixes #51

### CODE REVIEW

**Comment by Siubaak** [comment]
Function executions will bypass the global `execution`, and step the instruction codes on their own instead. Your modification will get failed in the following case:

```
interpreter.run(`
  (function () {
    while (true) {}
  }){}
`);
```

**Comment by rohanchandra** [comment]
@Siubaak Good point!

I've updated this PR to observe changes to the program counter from a subclassed `State` and also added a test case.

**Comment by rohanchandra** [comment]
@Siubaak Can we get a new NPM package release for `sval`?

**Comment by Siubaak** [comment]
@rohanchandra No unfortunately. I haven't passed all tests....

**Pull request merged**
