### PR TITLE
Rhino Runtime

### PR DESCRIPTION
**Pull request by Patrick-ring-motive**
I had to make some slight modifications to get this working in the Rhino runtime that is used by legacy Google Apps Script projects. The required changes are a result of the interpreter not evaluating dot notion on the following key words and needing bracket notation.

`.return` changed to `['return']`
`.throw` changed to `['throw']`
`.var` changed to `['var']`
`.const` changed to `['const']`
`.catch` replaced with a try/catch block

and lastly there is a lack of `global` variable so the script is prefixed with a top level `this.global=this;`.

### CODE REVIEW

**Comment by Siubaak** [comment]
The files in `/dist` are the built output from source code in `/src`. Once we change the source code and build, the `sval.gs` will differ from the latest built output.

I think a better way to handle your issue is to maintain a repo on your own. In your repo, treat sval as a submodule, and run a local script to build the sval and replace the keywords you listed above by regex. Making this automated proccess ensures the `sval.gs` to be the same as the original sval built output all the time.

**Comment by Patrick-ring-motive** [comment]
Yeah that should be easy enough. Famous last words.

**Comment by Patrick-ring-motive** [comment]
Regex is kind of the bane of my existence but I got it working. Now just need to automate it.

```
async  function updateSvalGs(){
    let text = await(await fetch("https://raw.githubusercontent.com/Siubaak/sval/master/dist/sval.min.js?"+new Date().getTime())).text();

    function rhinoify(str,word){
      str = str.replace(new RegExp(`([^"'\`]) *\\. *${word}([^A-Za-z_])`,"g"),`$1["${word}"]$2`)
      return str.replace(new RegExp(`([^A-Za-z_"'\.])${word}( *:)`,"g"),`$1"${word}"$2`);
    }

    const words = ["var","const","return","throw","catch","finally"];


    for(let i=0;i<words.length;i++){
    text = rhinoify(text,words[i]);
    }
    text = 'this.global=this;'
    return text;
}
```

**Comment by Patrick-ring-motive** [comment]
The automation seems to be working. The latest update got pulled in automatically.

**Pull request closed without merging**
